spring.application.name=01_Mini_Project_User_Mgmt_App
spring.datasource.url=jdbc:h2:mem:user_mgmt
spring.datasource.username=rajputsachin
spring.datasource.password=Albert9313@
spring.datasource.driver-class-name=org.h2.Driver
